# CI build to validate PR changes before merging

name: ace-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: tdolby/experimental:ace-minimal-12.0.8.0-alpine
      options: -u 0
      env:
        LICENSE: accept
    steps:
      - name: Install git
        shell: bash
        run: |
          unset LD_LIBRARY_PATH
          apk add git
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        # This option causes the submodules to be pulled in
        with:
          submodules: 'true'

      - name: Build the application and test it
        shell: bash
        run: |
          # This shell has mqsiprofile already loaded
          echo "Running build and unit test"
          ./build-and-test.sh
